Add Logical Color Combinations
Poncedeleon100/ktane-cruel-modkit pull request #14
Opened 2024-08-27 22:46 UTC by llPlayll

2024-09-06 14:16 UTC, Poncedeleon100 requested changes

2024-09-06 14:16 UTC, Poncedeleon100 commented on Assets/ModScripts/Submodules/LogicalColorCombinations.cs
> +using Random = UnityEngine.Random;
```suggestion
﻿using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using Random = UnityEngine.Random;
```
Some of these usings aren't necessary

2024-09-06 14:16 UTC, Poncedeleon100 commented on Assets/ModScripts/Submodules/LogicalColorCombinations.cs
> +    public LogicalColorCombinations(CruelModkitScript Module, int ModuleID, ComponentInfo Info, bool Vanilla, byte Components) : base(Module, ModuleID, Info, Vanilla, Components)
```suggestion
    public LogicalColorCombinations(CruelModkitScript Module, int ModuleID, ComponentInfo Info, byte Components) : base(Module, ModuleID, Info, Components)
```
Remove the Vanilla bool

2024-09-06 14:16 UTC, Poncedeleon100 commented on Assets/ModScripts/Submodules/LogicalColorCombinations.cs
> +    string[] finalPairs = new string[2];
These fields can all be readonly, along with the solvedLEDs and solvedColors lists

2024-09-06 14:16 UTC, Poncedeleon100 commented on Manual/HTML/Logical Color Combinations.html
> +    <link rel="stylesheet" type="text/css" href="Css/normalize.css">
```suggestion
    <link rel="stylesheet" type="text/css" href="css/normalize.css">
```
This shouldn't be capitalized

2024-09-06 14:16 UTC, Poncedeleon100 commented on Manual/HTML/Logical Color Combinations.html
> +        .operator-table td { font-size: 80%; }
These custom classes should follow the following naming convention:
`.module-name-class-name`

2024-09-06 14:16 UTC, Poncedeleon100 commented on Manual/HTML/Logical Color Combinations.html
> +                        <th>GREEN</th>
These cells could use the actual color as the background color so it looks a bit nicer (like in Metered Button and Who's Who's manuals). If you do add this, make sure that you use the same classes used in the other manuals but add another one for grey

2024-09-06 14:16 UTC, Poncedeleon100 commented on Manual/HTML/Logical Color Combinations.html
> +                </ui>
Replace the `<ui>` tag with the `<ul>` tag throughout the document

2024-09-06 19:11 UTC, Gameplushy commented
In the manual, use the empty set symbol instead of 0*

2024-09-06 20:09 UTC, Poncedeleon100 requested changes

2024-09-07 02:40 UTC, Poncedeleon100 approved these changes

2024-09-07 02:40 UTC, merged